version: 1
schemas:
  Dataset:
      required:
          - name
          - spatialCoverage
          - temporalCoverage
          - variableMeasured
          - url
      recommended:
          - version
          - description
