version: 1
schemas:
  Dataset:
      required:
          - name
          - spatialCoverage
          - temporalCoverage
          - variableMeasured: PropertyValue
          - url
      recommended:
          - version
          - description
